### ISSUE TITLE
AI spams way too many defenseless cities

### ISSUE THREAD

**Issue by bvanevery** [tnevolin/thinker-doer#104]
It's the single biggest problem with WTP's play.  The AI has to be wasting incredible amounts of resources on this.  It probably also confuses the hell out of it later, when it's time to be in a war with someone.  All this "frontage" that the enemy can come through.  Most of the game ends up being like a hot knife through butter, if you finally decide to invade.

The AI needs to transition from a "colonization footing" to a "war footing", and be aware of the most general circumstances, where colonization is no longer helpful or appropriate.  Like when another faction is close enough to be considered a neighbor, and that neighbor is becoming hostile.

**Comment by tnevolin** [comment]
#296
