### ISSUE TITLE
Minor issue - Readme out of date: Fanatic +50% buff no longer a feature as of v255

### ISSUE THREAD

**Issue by Mactaverum** [tnevolin/thinker-doer#109]
Readme states that the Fanatic trait for Believers was increased from +25% to +50%

This change is not reflected in alphax.txt or believe.txt where the bonus is +25% in v301

Looking through changelogs and versions this buff was reversed in v255 and has remained +25% ever since (there is a minor typo with this log such that you can't search for believe to spot this easily, nor does it mention the keyword fanatic)

I haven't played SMAC in probably 20 years and your mod ideas look great, thus was reading your readme fairly closely so noticed when picking factions for first time. :)

**Comment by tnevolin** [comment]
@Mactaverum
Should be restored everywhere to 50% now.
