### ISSUE TITLE
AI should evaluate neighbor threat and build defensive units and structures accordingly

### ISSUE THREAD

**Issue by tnevolin** [tnevolin/thinker-doer#11]

**Comment by bvanevery** [comment]
This is a huge and very noticeable problem, particularly when combined with the AI's propensity to spew lots of nearly defenseless cities.  The AI basically has no "reaction radius" when an enemy invasion force is inbound, or even when the AI starts to lose a whole bunch of defenseless cities in a region.  For the most part it sits around and does nothing, which is one of the hallmarks of very bad / incompetent AIs in 4X games.  That's a pity when putting one's work in front of the r/4Xgaming crowd.  The stock AI does display somewhat more competence, even if its ability to react is also limited.  And of course, not having altered it, I don't get so much blame for its limitations in my own modding work.

**Comment by tnevolin** [comment]
I actually already added this feature to recent version. Now it evaluates the thread and bumps military production priority. Maybe not that much so it requires further tuning. Or maybe it does but not use them best which results in perceived defenseless. Let me play with it a little more.

**Comment by bvanevery** [comment]
You mean in version 284 ?  I have not played that version.  My last game, that I quit over tech leakage, was version 282.

**Comment by tnevolin** [comment]
No. Some time ago. v230 when it started. Of course, it may get enhancement along the way.

**Comment by tnevolin** [comment]
#296
Should be included now. Accumulate defensive units and build structures.
