### ISSUE TITLE
Improve Echelon Mirrors 

### ISSUE THREAD

**Issue by OmanovicEdo** [tnevolin/thinker-doer#122]
To make them more useful add +0.5 minerals to Mirror tile per adjacent Solar Collector. I would also consider reducing Eco Damage from +6 to +4. 

The function would be to be a bit more spammable improvement that replaces Solar Collectors to save them from being replaced by forests. They also produce little energy in general compare to Boreholes now and sea tiles as well. Sea base can easily produce enough that you dont need to bother with Solar Collectors.

I think overall it will be a minor improvement.. extra few points of energy in some bases, something to work on when formers finish everything else important.

**Comment by tnevolin** [comment]
I will keep the same computation logic to add bonus to collector and not mirror. The sum will be about the same for 50-50 mix.

**Comment by tnevolin** [comment]
Implemented.
