### ISSUE TITLE
Sea tiles, Tidal Harness and energy

### ISSUE THREAD

**Issue by OmanovicEdo** [tnevolin/thinker-doer#123]
Nerf Tidal Harness energy: 3 -> 2. Its so good that we dont even need to build Thermocline Transducer.
Nerf Tidal Harness production time from 4 -> 6 turns.

Nerfing energy overall.. sea bases are spammed A LOT.. they dont have many minerals but produce ton of food and energy.

**Comment by tnevolin** [comment]
> Nerf Tidal Harness production time from 4 -> 6 turns.

Is is same as collector. They share the time. Will affect both.

**Comment by OmanovicEdo** [comment]
Yes this  ratio 3:1 is energy nerf so that is enough then, no need to change this.
