### ISSUE TITLE
TF + HF, Eco damage, Energy and Psych

### ISSUE THREAD

**Issue by OmanovicEdo** [tnevolin/thinker-doer#124]
Tree Farms and Hybrid Forests are so overloaded, plus forests are good in general, that it is no wonder some people just build forest everywhere + TF + HF and have great yields and no issues.

So, as the idea is not  to ruin the game, but to improve balance and gameplay, while keeping this strategy I would nerf couple of things.

* Tree farm: 120 min 3 maintenance. Seems good as is.
+50% ECON -> Nerf to 25%.
+50% PSYCH -> Nerf to 25%.
+50% ECO DMG reduction -> Nerf to 35%.

Still gives +1 NUTRIENT. The facility will be plenty strong even if nerfed more.. which we dont have to do I think.

Result: Nerf overall energy output, psych nerf that goes with new psych system.. also makes other improvements that give +psych more relevant. Eco damage nerf because it is completely op in conjuction with HF, eliminates good part of ECO DMG mechanic from the game.

* Hybrid forest: 240 min, 4 maintenance -> Buff to 180 min 4 maintenance.

+50% ECON -> Nerf to 25%.
+50% PSYCH -> Nerf to 25%.
+50% ECO DMG reduction -> Nerf to 35%.

Still gives +1 NUTRIENT. I would consider nerfing +1 ENERGY completely here. This turns forest to 3-2-1, and makes solar collectors, echelons and boreholes more relevant. Nerfs overall energy. Helps ALOT to keep farms and solar collectors on the map.. since its legit strategy to just replace everything with forests since they are so good. Cheaper production cost is there to balance nerfs.

Considering how HF combos with TF its still very strong facility, just less broken.

Still worth it to cover whole map with TF+HF.. just gonna have less energy and more drones, plus have to fight more eco damage.
Eco damage nerf will make

**Comment by tnevolin** [comment]
> Tree farm: 120 min 3 maintenance. Seems good as is.
It is currently 160/4.

**Comment by OmanovicEdo** [comment]
Yeah my  bad I am switching version so mixed things up. Tree Farm was looking good -, can be built in reasonable time, also can be rushed somewhat easily with energy. I think at 120/3 it is too cheap/quick  and easy to rush. I would leave it at 160, but cut maintenance then to 3. Even nerfed Tree Farm is super op, got them quite easily in my Miriam game with current cost.

HF comes later, 160 is often only 4-5 turns plus you can rush so I would go for 200. Should be harder to get since it stacks and boosts bonuses even higher. I would like it to be a bit more of a luxury for strong bases rather then quicker useful yield booster spammed everywhere. You feel good when you get this. Maintenance 6 is dumb.. cut to 4. so 200/4.

I think in practice you can put 2-3 turns of minerals into these and lots of people will just quick rush it. Wanna keep game harder as well ; )

**Comment by tnevolin** [comment]
HF comes much later in the game when faction production power is more than twice as big. 200 is not that big diff from 160. Let us make it at least 1.5 times more expensive.

160/3, 240/4 ?

Game is build on whole number operations. Computing 35% would be unusual. How about each cuts eco damage in half? This way both will do 3/4 together.

**Comment by tnevolin** [comment]
Completed.
