### ISSUE TITLE
Teach AI to populate bunkers with defensive units

### ISSUE THREAD

**Issue by tnevolin** [tnevolin/thinker-doer#17]

**Comment by bvanevery** [comment]
You disabled bunkers.  A wise move, which I did in my own modding eons ago.  It only provides routes for human invasion and is of no advantage to the AI.  Game mechanically, it is also irrelevant chrome.  Good riddance.  You can close this.

**Comment by tnevolin** [comment]
Yes. This is for future evolution. I actually plan to team AI to use them!

**Comment by bvanevery** [comment]
Per #16, please sleep on it, think better of it, and close both.  This is a complete waste of your developer time.

**Comment by tnevolin** [comment]
Closing this too.
