### ISSUE TITLE
Rework probe team success rates

### ISSUE THREAD

**Issue by tnevolin** [tnevolin/thinker-doer#18]
Make them more smoothly distributed based on morale, algorithmic enhancement, HSA.
This is to make probe morale matter less in success rate and algorithmic enhancement more.

**Comment by nevill-spb** [comment]
What do they currently look like? What is the formula?

Does it take into account the PROBE rating of the defending faction? I think it doesn't, but it would be awesome if it did. It would give the Covert Ops centers some meaning, and place more importance on the PROBE settings which are an afterthought for most players.

Some actions are unnecessarily hard compared to the benefit they bring. I never got much mileage out of stealing money... even from the AIs who hoard them. Even elite spies die from time to time, and their cost is ultimately greater than what they could steal from border bases.

**Comment by tnevolin** [comment]
http://alphacentauri2.info/index.php?topic=2761.0
It does take many things into account including enemy rating, COC, etc. The thread above doesn't even list them all.

You are right that the formulas are quite sloppy and not balanced. Genetic warfare 100% success ratio? Please. I cannot even change the RISK of this action because it is shared with other actions. 😥
There is no much we can do without **complete** rewrite of probe function which is huge and convoluted.
These are all subjects to discussion on forum.

By the way, I was about to cancel this one specifically due to heavy hard-coded source. Ugh. Good idea but I would never finish it completely.
The only thing I think I can do is demand Genetic Warfare is executed by only Elite probes. This way one needs COC or promotions in addition to high PROBE rating to grow such probes.

**Comment by tnevolin** [comment]
Changed Genetic Plague risk to 2. I think this is all I want to do with this for now. The rest of it is more or less fine. Will create more tasks if I need other changes.
