### ISSUE TITLE
Enhance base location search algorithm

### ISSUE THREAD

**Issue by tnevolin** [tnevolin/thinker-doer#19]
Currently colony is doing it somewhat jerky.

**Comment by nevill-spb** [comment]
It should probably check whether the destination is eligible every other turn. I have a save where my Pact Hivemate has a Colony Pod with an order to move into another faction's base which Hive has a vendetta with. Apparently Sparta settled there first, and the Hive didn't get the memo.

Then again, check it too often, and we may have pods constantly cruising from one end of the empire to the other, never settling in one place.

**Comment by tnevolin** [comment]
#206
