### ISSUE TITLE
New prototype costs are inconsistent

### ISSUE THREAD

**Issue by nevill-spb** [tnevolin/thinker-doer#27]
Okay, so I am playing with the new rules for prototype component costs.

The settings in alphax.txt are restored to the initial 50%:
50,      ; Extra percentage cost of prototype LAND unit
50,      ; Extra percentage cost of prototype SEA unit
50,      ; Extra percentage cost of prototype AIR unit

Rover chassis and transport module costs are set to the following values:
Speeder,M1,   Rover,M1,      Defensive,M1,   Skirmisher,M1,2, 0, 0, 0, 2, 2, Mobile,   Dragon,M1,         
Troop Transport,      Transport,      0, 7, 3, -1, Mobile,

The Workshop displays the cost of the prototype as 5 mineral rows:
https://imgbox.com/S5liI5Q6

 while the actual production only takes 4 mineral rows:
https://imgbox.com/2vH5SKt8

Is there a reason for this?

**Comment by tnevolin** [comment]
Let me check.

**Comment by tnevolin** [comment]
Indeed. I found the problem in underdeveloped code. My mistake. I guess with so many ASM coding in so many places I got tired and missed one.
Great catch! We need more people like you. 👏

Fixed in 168. Now extra prototype cost should use same formula for designer and base production.
