### ISSUE TITLE
Is it possible to treat Pact Brother/Governor status as temporary infiltration?

### ISSUE THREAD

**Issue by nevill-spb** [tnevolin/thinker-doer#29]
Proper infiltration has one massive UI improvement over its simulacra: it shows you production in all of the faction bases overland. A pact brother offers the same information if you click on the bases, but does not display it on the map. You have to manually click on each and every base to see what they are building. It is incredibly annoying.

Is it possible to treat those infiltrations the same, at the very least when it comes to UI?

I would also question whether Rose bonus (steal a tech known to 3 factions you have infiltration with) should be triggered by Pact Brothers and governorship. Personally I'd say it should, but this may be up to debate.

**Comment by tnevolin** [comment]
I think it is. There is a "spying" check in the game that verify if at least one is true: infiltration is active, you have empath guild, you are planetary governor. So I can add "being in pact" to the list.
I can do it either just for the purpose of displaying production on a map or globally - wherever this check is used. Based on your knowledge, is there ANY place in a game where being in pact should NOT provide all benefits of spying?

**Comment by nevill-spb** [comment]
> Based on your knowledge, is there ANY place in a game where being in pact should NOT provide all benefits of spying?
Can't think of one off the top of my head. Where does the game use those "spying" checks?

> There is a "spying" check in the game that verifies if at least one is true: infiltration is active, you have empath guild, you are planetary governor.
The only one that comes to mind is Roze's ability. But does Roze even get techs based on this check? I thought only hard infiltration counts towards her bonus.

**Comment by tnevolin** [comment]
She doesn't even need infiltration for her bonus to work in Thinker/WTP. So don't worry about her. She'll be unharmed.
Implemented in #167.
