### ISSUE TITLE
AI Diplomacy bugs

### ISSUE THREAD

**Issue by nevill-spb** [tnevolin/thinker-doer#30]
It is possible to sell a pacted AI more tech than the AI has credits, causing it to lose facilities next turn. It is a number 1 cause for AIs losing HQ. Can a check be implemented to verify they have the money before making a transaction? These checks seem to be in place for loans.

There was a bug in vanilla with an AI improperly evaluating bases, and offering its best ones for measly pop-1 base. The bug was supposedly fixed by scient's patch, but I don't know if Thinker/WtP includes it.

There are options and lines I almost never see in AI diplomacy. When they are offering a tech trade, you can often offer a counter-proposal for another tech, which they then can turn down. I've never seen anyone but Yang turn down such a proposal. What governs this decision? I'd like to see it more often as AIs are almost omnivorous when it comes to tech, trading Tier 6 for Tier 1-2.

(actually, can a tier factor in the tech value, now that the techcost formulas got changed?)

It is possible to extort an AI for money. It is most often seen with surrendered AIs as they can't go against their conqueror, but they can make the process very tedious. Especially Yang, who can sit on a bank of 100+ credits and offer it to you in 9-credit packages. Can there be set a minimum of what they can offer you? Coming to Yang with the same threat for 20 times in a row just to take what he can't afford to keep adds nothing to the game.

Sometimes an AI would spam messages at you at every opportunity. Sometimes they do it to sue for peace, and sometimes just to insult you. I wish there was an option to block them out for a turn, because being contacted dozens of times every time my units make contact only to be told that I'll pay for my atrocities is annoying more than it is amusing. Are they making me pay with my time?

**Comment by tnevolin** [comment]
I'll look into tech trading.
Thinker includes Scient's. Would you mind testing this specific case?

Special diplomacy hardcoding, I suppose. Yang doesn't accept other technology. Miriam never ever trade anything for money, etc. I can check it but it doesn't seem something game breaking so will be low priority.

Good point about tech value. Need to check on that.

Didn't understand about extorting. Are you talking about borrowing?

Are you talking about the one screen one button popup where they swear to never end the war? Don't think anything could be done about the last. They just programmed to respond if you contact them. If it happens few times a turn so be it. There is no **counter** on number of encounters and it would be impossible to stick it somewhere in the game.
I never experienced them doing that multiple times a **turn**, though. Do you have a save?

**Comment by nevill-spb** [comment]
> Special diplomacy hardcoding, I suppose. 
Can you verify? I am okay with the answer "only Yang does that", it's that the possibility of some underused setting not available because of some bug that bothers me.

> Didn't understand about extorting. Are you talking about borrowing?
Yes. Give surrendered Yang 100 credits, ask him to lend you money, "or else". He'll give you them in the increments of 9 credits. I've seen him go as low as 3! He will get another 3-9 if you ask him again. And again. And I think it'd be better if he gave you however much he is willing to with the corresponding hit in relationships without me spamming the option ten times.

> Are you talking about the one screen one button popup where they swear to never end the war? Don't think anything could be done about the last. They just programmed to respond if you contact them. If it happens few times a turn so be it. There is no counter on number of encounters and it would be impossible to stick it somewhere in the game.

That is fine, the problem is that they consider it contact if your units come close to them. I've seen it happen 20 times per turn. I am not kidding! 20 times of THEM calling ME to insult me and hang up, only to pick up the phone 5 seconds later after I move my unit. I was hoping there could be a mute setting to ignore them until I call them or something.

I don't think I have a save on me now, but I'll attach it if I observe a similar behavior. Normally they want to contact you every time you capture their base, so this can be observed every time you capture several.

**Comment by tnevolin** [comment]
> > Special diplomacy hardcoding, I suppose.
> 
> Can you verify? I am okay with the answer "only Yang does that", it's that the possibility of some underused setting not available because of some bug that bothers me.

I feel you interest but should disappoint you a little. My bandwidth is pretty narrow as well as my memory span 🤣
I tend to embark on small changes if possible and push them out of the door sooner to not clutter my simple development environment and be free for bug fixes if any.

My secret is that I am sitting on already heavily disassembled IDA database from Scient and Induktio. They save me 98% of research. Any additional disassembling is a huge work. You can create a separate task on that and bug me periodically. Sometimes I may have bigger time slots.

> > Didn't understand about extorting. Are you talking about borrowing?
> 
> Yes. Give surrendered Yang 100 credits, ask him to lend you money, "or else". He'll give you them in the increments of 9 credits. I've seen him go as low as 3! He will get another 3-9 if you ask him again. And again. And I think it'd be better if he gave you however much he is willing to with the corresponding hit in relationships without me spamming the option ten times.

That is again the complex diplomatic algorithms those may not have 100% coverage in all edge cases. Like with surrendered faction that probably uses same algorithm as for not surrendered one in term of amount but not in term of willingness. I wouldn't bother with this one specifically because there could be multitude of others equally annoying things sitting in corners here and there.

Besides, I don't really understand how is this an extortion if you have to pay them back with interest?

**Comment by tnevolin** [comment]
#177
Only for explicit cash for tech offer. Could affect all trades of such type but not sure. Let me know if other branches need patching.
