### ISSUE TITLE
Knowledge obsoletes University

### ISSUE THREAD

**Issue by bvanevery** [tnevolin/thinker-doer#48]
Anyone who learns and can use Knowledge, i.e. anyone other than the Believers, gains a +5 RESEARCH advantage.  This is overwhelmingly better than the University's +2 RESEARCH.  In the real world, the University is currently a no advantages, all disadvantages faction.  A free Network Node is _not_ worth a drone every 4 citizens, as you'll have to spend on a facility and its maintenance to overcome that.  A paltry RESEARCH bonus compared to the competition, is not worth extreme -2 PROBE vulnerability, which makes enemy mind control 50% cheaper and more likely to succeed.

The University could be beefed up, or Knowledge could be toned down.

**Comment by tnevolin** [comment]
I thought just adding multiplier on top of knowledge bonus should achieve about the same effect but is linear.
Like each step on RESEARCH scale gives 20%-25%-30% instead of 10% vanillas.

**Comment by bvanevery** [comment]
Yes, and the point is anyone who chooses Knowledge is getting +50% RESEARCH per the #SOCRESEARCH table.  Which is way better than the University's +20% faction ability.  A SE choice shouldn't make you into a 2.5x better researcher than supposedly the best researcher in the game.  And this is on top of whatever Transcend bonuses are buried in the code somewhere.  AI factions clearly are already goosed along somehow, so the University's bonus in the hands of a human player, really doesn't do much.

**Comment by tnevolin** [comment]
I don't think giving flat bonus to anybody is a good idea.

**Comment by bvanevery** [comment]
I don't understand what you mean.  There's a RESEARCH faction called the University that gets +2 RESEARCH.  There's an ECONOMY faction called the Morganites that gets +1 ECONOMY.  There's a MORALE faction called the Spartans that gets +2 MORALE.  Gaians get +1 PLANET.  You think this idea of deviating factions along different play axes, is basically wrong?  What would you do instead?

**Comment by tnevolin** [comment]
> What would you do instead?

https://github.com/tnevolin/thinker-doer/issues/48#issuecomment-723469854

**Comment by bvanevery** [comment]
You are saying that you want a midgame SE choice to render someone's choice of faction obsolete?  Why then have different factions at all?  You could go back to Civ II and have everyone start with their nation, with all nations having exactly the same capability at game start.  Factions do give narrative flavor but that's just a skin.

**Comment by tnevolin** [comment]
Sorry. Didn't understand that.

**Comment by bvanevery** [comment]
Your previous comment, was merely a link to this Issue.  I _thought_ you perhaps meant something by that, but perhaps your answer was just a typo.

**Comment by tnevolin** [comment]
It was a link on my first comment in this issue.

> I thought just adding multiplier on top of knowledge bonus should achieve about the same effect but is linear.
Like each step on RESEARCH scale gives 20%-25%-30% instead of 10% vanillas.

**Comment by bvanevery** [comment]
alphax.txt for version 190 says:
```
#SOCRESEARCH
-5, Labs research slowed by 50%
-4, Labs research slowed by 40%
-3, Labs research slowed by 30%
-2, Labs research slowed by 20%
-1, Labs research slowed by 10%
 0, Normal research rate
 1, Labs research speeded by 10%
 2, Labs research speeded by 20%
 3, Labs research speeded by 30%
 4, Labs research speeded by 40%
 5, Labs research speeded by 50%
```
Is it wrong?

**Comment by tnevolin** [comment]
It is correct. The same exactly numbers as in vanilla. Nothing changed.
I understand you have created this task for _future_ changes. It is not yet implemented. We are just discussing it.

You proposed to add +50% research to all faction with positive inherent RESEARCH. Did I understand this correctly?

I, in turn, noted that this any flat bonus would be difficult for people to understand and it also would be unfair granting the same bonus to faction with +1 RESEARCH AND +3 RESEARCH inherent bonuses.

My counterproposal is to just multiply the RESEARCH effect by 2 times to make this effect valuable and noticeable. This way -5 RESEARCH would just stop research progress completely and +5 would double it. I think it would beef up its value. Even though others would steal from such faction it still can keep up ahead of others.
Optionally, we can multiply it even more than 2 if you think it makes sense. However, -5 rating would then give negative effect. Which is weird.

**Comment by bvanevery** [comment]
> You proposed to add +50% research to all faction with positive inherent RESEARCH. Did I understand this correctly?

I did not.  I said:
>>The University could be beefed up, or Knowledge could be toned down.

In fact I have no idea where you got the other idea.

**Comment by tnevolin** [comment]
194
