### ISSUE TITLE
eliminate fungal towers from landing sites

### ISSUE THREAD

**Issue by bvanevery** [tnevolin/thinker-doer#49]
After extensive testing of faction_placement=1 vs. the stock faction placement algorithm, I conclude that the main thing the latter does better, is it somehow eliminates fungal towers from some radius around landing sites.

Fungal towers near to starting locations, are formidable barriers as they quickly become unkillable in the early part of a WTP game.  It takes a lot of Scouts to suicide into them, and that productivity is typically not available at the beginning of the game, when the barrier has the most profound effect on early colonization.  They typically take up 9 squares of fungal pollution.  They make it very difficult to settle without being next to the patch of fungus.  Mindworms that have been stirred up by pod popping tend to move though them, and fungal towers are capable of spawning their own mindworms.

**Comment by tnevolin** [comment]
I seriously doubt Thinker placement has anything to do with fungus or towers. It just tries to spread factions a little spatially.
Game weakens aliens in half for first 15 turns so it makes baby tower weaker than scout. However, if this is not enough, I propose to weaken aliens even more to make early development equally easy for all.
Something like 40% of their strength on turn 0 + 2% every turn until turn 30 when they regain their full strength.

**Comment by bvanevery** [comment]
Yes, the stock game has a better faction placement method than Thinker does, with respect to fungal towers.  That is the reason for filing the Issue.  If it were trivial or easy to adjust, I would have just counted on you to make some ready decision about it, in reaction to my dev thread posts.  This is work.  It's enough work to warrant tracking.

The method could be "place towers, place factions, remove fungal towers within some radius", or it could be "place factions, place towers so long as they're outside a faction's radius", or "find a radius that doesn't have fungal towers in it, place faction".  The first 2 methods would still suck for the Usurpers.  I wouldn't worry so much about the Caretakers and the Cultists, as they're not especially disadvantaged by fungus barriers.

I don't want aliens weakened, I want fungal towers weakened, or not there.  Even if they can be killed, 9 fungal squares is a _lot_ of fungus to put near a starting base.  It encourages the impenetrable fungal maze phenomenon, which is a pretty sucky way to start, even at the typical great distances between Thinker factions.

I also think 30 turns is probably not long enough to get anything done, during initial settlement.

**Comment by tnevolin** [comment]
How about taking their 50% bonus away?

**Comment by bvanevery** [comment]
Fungal towers have a 50% defense bonus?  Is that hardwired in the binary?  I don't see any factor like that in alphax.txt or thinker.ini.

It would be worth trying.  If a 50% defense bonus is from stock SMACX, well that also had 3:2 offense:defense ratio.  Not true in WTP.

**Comment by tnevolin** [comment]
Removed fungal tower defense bonus in #196. Hope this is enough with 1:1 combat and weakened aliens. Let me know.
