### ISSUE TITLE
mindworms double spawn too early

### ISSUE THREAD

**Issue by bvanevery** [tnevolin/thinker-doer#50]
When popping supply pods, I've gotten 2 mindworms surrounding my Scout as early as MY 2116.  This is way too early.  In that particular test game, due to rampant fungal maze problems I'd only just gotten my 2nd city settled.  I don't have the productivity to have extra Scouts to fend off a bunch of extra mindworms.

Generally speaking such a surrounded Scout will die.  Or if it's surrounded by a mindworm and a spore launcher, the mindworm will inflict a bad wound on the Scout, so that it cannot attack the 2nd unit.  Then the spore launcher destroys all the terrain improvements in the region, which could be the Borehole Complex, or a forest I just took a long time to make, or similarly a mine, or forest that I got from a pod pop, that I actually needed to mitigate the rampant fungal maze problem.  A surviving mindworm can do it too, it's just a little slower than a spore launcher.

These early double attacks are a janking.  They suck, and they happen too much.

Every Civ game has had some kind of proscription on "rampant barbarian activity" until sometime in the future.  60 to 80 turns is a typical threshold, allowing the player time to actually explore and actually get something done.  I know that WTP passed through a phase where it thought all manner of threatening mindworm mayhem was a good idea.  I think the design is evolving past that point, and that play mechanic is no longer appropriate.

Actually in that aforementioned MY 2116 test game, _both_ mindworms survived.

**Comment by bvanevery** [comment]
Just had a game in MY 2120, where I had a Unity Rover and a Scout, go against a spore launcher and a mindworm, that came from a supply pod.  They _both_ attacked the spore launcher and they _both_ died.  The Rover hadn't moved.  The Scout had only 1/3 move remaining, and could not finish off the weakened spore launcher.  The spore launcher appeared within range of _two_ Borehole Complex boreholes, and now it will destroy them.  I quit the game, and won't play anymore games until this kind of double mindworm event is pushed to later in the game.  It's a dealbreaker.

**Comment by bvanevery** [comment]
I've gone back to playing my own mod, which uses the stock binary.  I find that I get early double mindworm events as well, as soon as MY 2115 or MY 2119.  I didn't realize this was stock binary behavior.  The difference for WTP, is these events are of higher consequence.  In stock, you can always kill at least 1 of the mindworms, due to the 3:2 psi offense ratio.  Also it does not take forever to build a forest, so losing one you made to a spore launcher isn't as painful.  Losing a Mine or a Borehole Complex is still painful though.

**Comment by tnevolin** [comment]
It seems like a relatively minor thing. I usually have 3-4-5 scouts right off start and they are cheap to build more as needed. Their support is limiting factor not the cost. So once I lose one I rebuild one just to keep in support limit. I expect one-two of them to lose in worm fight after turn 15. That is normal. So do AI factions. They seem to lose scouts on a regular basis and it doesn't stop their expansion a bit.

**Comment by bvanevery** [comment]
My 1st paragraph again, answers what you you just wrote:

> When popping supply pods, I've gotten 2 mindworms surrounding my Scout as early as MY 2116. This is way too early. In that particular test game, due to rampant fungal maze problems I'd only just gotten my 2nd city settled. I don't have the productivity to have extra Scouts to fend off a bunch of extra mindworms.

**Comment by tnevolin** [comment]
I understand your frustration. I had same things in the past vanilla games. Usually just restarted if I felt absolutely surrounded.
This is concrete feeling but it is difficult to point a finger on "something that needs to give". Don't know what to do with this statement from technical point of view.
Game is too hard at times? Too much randomness in events early game?

**Comment by bvanevery** [comment]
Fungal maze generation, starting position evaluation, restricting number of mindworms that appear based on turn, are possible ways of addressing the problem.  I don't know which is technically easiest to implement.  I do not think you should change the offense:defense psi ratio as I think that's what makes your mod play differently.  But it does have noticeable consequences for early game events.  Vanilla events were not designed with mindworms this tough.

**Comment by tnevolin** [comment]
Oh yes. They are possible ways but you are thinking too much of me.
😉
This is too much of a new design I don't have time for.

I can prolong the period of time while worms are fighting on half of the strength. That is probably easy. Will it work?

**Comment by bvanevery** [comment]
Probably would work.  Would suggest making it available as one of the many variables in thinker.ini, in case it's still too early.

**Comment by tnevolin** [comment]
#197
Feel free to recommend good value for that.

**Comment by bvanevery** [comment]
Either the turn setting doesn't work, or the "half strength" mindworms are still too tough for the beginning of the game.  I tried turn 30 and it didn't help.

**Comment by tnevolin** [comment]
I have retested it and it seems to work. Please test it on "pause after each combat" and see what attack strength for aliens you have at what year. Or jus send me a save before that.

**Comment by bvanevery** [comment]
Seems to work in version 198.   aliens_fight_half_strength_unit_turn=30 is a more reasonable value.  It's very possible to have bad starts in fungal mazes.  I've tested a number of games now and 30 turns is better breathing room.  Triple mindworm pops tend to begin around then.  Just had one on MY 2127.

**Comment by tnevolin** [comment]
Cool. I'll set it to 30 default in future then.
