### ISSUE TITLE
Faction should stick to their SE preference even if it is not discovered

### ISSUE THREAD

**Issue by tnevolin** [tnevolin/thinker-doer#52]

**Comment by tnevolin** [comment]
#181

**Comment by bvanevery** [comment]
This is still bugged.  https://alphacentauri2.info/index.php?topic=21359.msg132783#msg132783
> Domai's Agenda is Eudaimonic, but he has gone Cybernetic.  WTP is inheriting Thinker mod's disregard for faction agendas.
>
>Pretty soon we'll be in the awkward position where I go Cybernetic, but then Domai jaws at me to go Eudaimonic, while he is Cybernetic himself!!
>
>I have both Domai and Aki Zeta5 as allies.  In a normal game, they would be ideologically incompatible with each other.

Saved game:
[Lal of the Peacekeepers, 2268.zip](https://github.com/tnevolin/thinker-doer/files/8006136/Lal.of.the.Peacekeepers.2268.zip)
I think I was playing version 283.

![class traitor](https://user-images.githubusercontent.com/734930/152600914-7a476b1f-407e-4d11-aa8e-91ccd0427561.jpg)

**Comment by tnevolin** [comment]
Found some social AI related bug in Thinker. Not sure it is related but I'll let him fix it.
https://github.com/induktio/thinker/issues/34

**Comment by tnevolin** [comment]
#285

**Comment by tnevolin** [comment]
On second thought how they should stick to something not yet discovered? Let's say they know all other models besides preferred. Which one they should stick to? Should it always be default one? How vanilla is doing that?

**Comment by bvanevery** [comment]
They use the default one.  Like Domain should have Future Society, None, until such a time as he knows Eudaimonic.  He's ideologically opposed to the other kinds of Future Societies.

**Comment by tnevolin** [comment]
Then I'll leave it as I fixed it. Should work.
