### ISSUE TITLE
remove useless predefined units

### ISSUE THREAD

**Issue by bvanevery** [tnevolin/thinker-doer#53]
The AI obsesses about producing the **Trance Scout Patrol**, **Trance Formers**, and **Trance Sea Formers** to an unhealthy degree.  I've seen games with 60 to 80 of these units, and not nearly enough cities to justify the outlay.  The excess of units runs the AI out of SUPPORT.  They are not competent units for defense, as there's no guarantee that an enemy will attack only with mindworms.  The wild mindworms aren't bad enough to justify quite so many units.  It's a big loss of productivity when Hypnotic Trance units are so much more expensive than their ordinary counterparts.

The AI is incompetent with unarmored **Infantry Probe Teams**.  It will try to use them on offense and will simply get them killed.  They only move 1 square and it's trivial to destroy them.

These are well studied problems of the stock binary.  I've observed AI obsessions and incompetences with predefined units for a long time.  You should never define a unit for player convenience.  It should only be used for telling the AI a good strategy.  The AI can totally bork the use of a unit, you just have to see what it does in practice.  I've had to remove lots of unit designs that I thought were a good idea, but weren't.  The AI can obsess, the AI can fail to use a unit properly, the AI can make good use earlier in the game and then overproduce it in the mid to late game when it's not useful anymore.

**Comment by tnevolin** [comment]
AI tuning is a tedious work. There are tons of parameters for production in thinker.ini. I can turn them up and down but there is no guarantee the result will be better. I suggest you go ahead and play with them and see if you like the result.

RE: trance units vs. regular ones. I don't see a big deal for computer to spend one more row per unit. Still support going to eat most significant part of production. Same suggestion for these as well. Try to cross them out of the list and see if it benefits AI. Then I'll store it as default.

**Comment by bvanevery** [comment]
I've already tested the removal of predefined Trance units for many WTP games now.  Surely you're reading your development thread?  I've also got years of experiencing watching the phenom in the stock binary.

I don't know anything about production parameters in thinker.ini.  What I do know is that after removing the predefined units, some factions can end up overproducing Scouts.  I would deal with that as a separate problem though.

**Comment by tnevolin** [comment]
Good. I'll teach it to not build trance sea/formers.
Not sure about trance scouts, though. They seem to be better choice as anti natives base defense.

**Comment by bvanevery** [comment]
Quit obsessing about anti-native defense.  You already toned down the native wild mindworms.  I wouldn't be playing WTP if you hadn't done that, as it was pretty awful before.  You don't need Trance Scouts everywhere.  The AI is not gonna suffer.  And your mindworms are not as powerful on offense as the stock game, so they're not as attractive for the human player.  Especially when facing off against a PLANET friendly faction, with all the psi defense bonuses, they just wear out.

What you _do_ need, are some real armored units with Trance ability on them.  I'm not convinced your policy of super expensive Hypnotic Trance ability is a good one.  But there's no point entertaining adjustments on that, until the "standard settings" for everything else are stable.  Balancing these settings is like pulling the threads on a sweater.

**Comment by tnevolin** [comment]
Fine. Let's exclude them.

**Comment by tnevolin** [comment]
256
* Removed Infantry Probe Team predefined unit.

As for trance units I'd like to keep them. They are only one row more expensive but protect from worm attacks pretty well. There is limited need for them so it won't be a constant drag for AI.
