### ISSUE TITLE
University is crippled

### ISSUE THREAD

**Issue by bvanevery** [tnevolin/thinker-doer#54]
The University's new +3 RESEARCH bonus still doesn't make it an awesome faction compared to AI factions on Transcend.  In practice, I consistently see them trailing other faction's research, not leading.  It's pretty insulting to be treated like the poor boy on tech when playing the University.  Ally gives a tech, tells you to guard this knowledge carefully, declares what a pleasant chat we've had, and cuts off the comm.

Meanwhile, they get a drone every 4 citizens.  A free Network Node is _not_ worth this, as you'll have to spend a lot more on happiness maintenance.

To add insult to injury, they're tremendously vulnerable to probe with -2 PROBE.  As though they actually have a lot of research capability, when they don't.

In the original game, the Virtual World compensates for the University's happiness deficiencies.  Although they're not guaranteed to have it as a starting tech, it's likely.  And in any event, it will soon be gained.  In WTP, the Virtual World tech takes forever to get, and then it's impossibly expensive to build.  This cripples the University specifically.

Similarly, in the original game the University can typically get the Hunter-Seeker Algorithm done.  It ain't gonna happen in WTP, as the University has no productive advantages, a happiness productive deficiency, and no in practice research advantage to get to it first.

In my mod, I got rid of the drone penalty and the probe penalty.  For a long time they still underperformed as an AI faction.  I even gave them a free Biology Lab for awhile.  Eventually something changed in my tech tree and they suddenly had an easier time, I'm not sure what.  So I don't give a free Biology Lab anymore.  But I do think getting rid of their onerous penalties is a good idea.  Their RESEARCH bonus just isn't that effective.

**Comment by tnevolin** [comment]
Makes sense. I'll schedule it for future change.

**Comment by tnevolin** [comment]
#195

**Comment by tnevolin** [comment]
fsdfsf
