### ISSUE TITLE
Alien Offense and Defense are overpowered

### ISSUE THREAD

**Issue by bvanevery** [tnevolin/thinker-doer#55]
WTP has too many combat bonuses, particularly for defenders.  The 25% Caretaker Defense bonus is particularly egregious, on top of all sorts of other bonuses for territory and base.  The Aliens shouldn't be superpowered factions.  In my mod, I removed their OFFENSE and DEFENSE bonuses.  If you keep them, they should be no higher than 10%, because of all the other bonuses in your mod.

**Comment by tnevolin** [comment]
You mean removing Alien combat bonuses? Sure. I am not particularly attached to them.

**Comment by tnevolin** [comment]
#201
