### ISSUE TITLE
partial payment calculation does not use faction INDUSTRY penalty

### ISSUE THREAD

**Issue by bvanevery** [tnevolin/thinker-doer#60]
Version 218.  I started a game as the Spartans.  They have -1 INDUSTRY.  1st time I went to Hurry a colonist, the "minimum to complete" calculation for partial payment said I needed to pay 35 credits to get my colonist done in 1 turn.  This was not correct.  I was left 1 mineral short of what was needed, so it took 2 turns.

I tried it a 2nd time, when it recommended 71 credits.  It again was off by exactly 1 mineral.  So it is not a linearly proportional error.  It is some kind of mismanagement of an endpoint constant, with respect to a -1 INDUSTRY penalty.

A 3rd time, it recommended 14.  I paid 15 and that was spot on.

Tried it when the recommendation was 3.  Actually spent 3.  It completed.  So probably below a certain amount, it works.

**Comment by tnevolin** [comment]
I need to check this computation with different industry. Thank you for pointing this out.
Do you have save? Do you remember how many minerals were already accumulated?

**Comment by tnevolin** [comment]
#220
Rounding problem. Set it to round up now. May still be off sometimes but this time it will be one brick more instead.
