### ISSUE TITLE
pillage with no relationship gives vendetta without warning

### ISSUE THREAD

**Issue by bvanevery** [tnevolin/thinker-doer#61]
It is common to end up with no diplomatic relationship at all with the Alien factions, when you're a human.  I am the Spartans, was knocking around Usurper territory.  With no relationship, it's perfectly legal to steal techs from them.  No vendetta is triggered.  I'm not sure how many other actions are perfectly legal, but I could swear that if an action like pillaging or raising land is illegal, then you get a warning telling you it is.  And then, do you want to do it anyways?  I get no such warning.

I don't know if this is vanilla behavior or not.

**Comment by tnevolin** [comment]
Didn't understand what exactly you want to change?

**Comment by bvanevery** [comment]
When you pillage a tile, if it's going to trigger a vendetta, the warning dialog box should come up telling you that this is going to happen.  And asking if you want to do it anyways.  You should not just silently have a vendetta initiate.

**Comment by tnevolin** [comment]
I'm afraid this is how it is done in game generally when you have no relations with the faction. You don't get a warning in this case. I'll check if it some single place easy to fix.

**Comment by tnevolin** [comment]
#222
