### ISSUE TITLE
ships do not have nerve gas available

### ISSUE THREAD

**Issue by bvanevery** [tnevolin/thinker-doer#62]
I've got nerve gas available for my land units just fine.  I need to get rid of Usurper sea bases.  I don't want to have to take care of those bastards.

**Comment by tnevolin** [comment]
Are you asking to give or not to give it to ships?

**Comment by bvanevery** [comment]
Maybe they didn't like that winning an X artillery duel, will depopulate a base!  Personally I think this is great / fantastic.  Of course, my whole reason to use X weapons is to eXterminate bases that I don't want to micromanage.  It may not be the best idea from a game balancing and difficulty standpoint, but it's a _great_ idea from a finish the damn game standpoint.

You can still pull this trick with X land artillery, although of course you need Neural Grafting to make such a unit.  With ships, since they're inherently both direct fire and artillery weapons, you can do it as soon as you get X weapons.

**Comment by tnevolin** [comment]
I don't have any opinion on that. Can enable it easily in alphax.txt.

**Comment by bvanevery** [comment]
Ships still don't have nerve gas available in version 252.  I notice that the original game didn't make it available.  In my mod, I've found it highly useful to allow it.  Especially in WTP, there are a _lot_ of bases to wipe out at sea.

**Comment by tnevolin** [comment]
I didn't do anything on that. The messages above seem to be some automatic notification about something else.
This issue is still pending.

**Comment by bvanevery** [comment]
Yep that's why I pinged it.  It's actually trivial to make the change.  It's a question of willingness to make it.

**Comment by tnevolin** [comment]
256
