### ISSUE TITLE
remove Energy Market Crash event

### ISSUE THREAD

**Issue by bvanevery** [tnevolin/thinker-doer#63]
The Energy Market Crash is already one of the worst, most horrible, unfun, disproportionately awful events in the vanilla game.  It's even worse in WTP, because of the absurdly high cost of Secret Projects and 6:1 credit exchange rate for SPs.  Trying to get even 1 SP done in the early to mid game is going to take either lots of Artifacts or stupendous, gigantic piles of cash.  _Almost_ accumulating that kind of wealth after 6 hours of play, and then having an Energy Market Crash, well it's dealbreaker territory for me.  And it's not like I didn't build any Energy Banks either.  I've played plenty of vanilla games where I've had the _Planetary Energy Grid_, and still gotten the Crash.  It's some of the worst game design that was done in the original game.

I don't think all random events should have to be turned off, just because this one event sucks so hard, and sucks so much worse in WTP.

**Comment by tnevolin** [comment]
#225
