### ISSUE TITLE
Morganic hab complex penalty description is wrong

### ISSUE THREAD

**Issue by bvanevery** [tnevolin/thinker-doer#64]
The Morganic faction description says you can't have a base with population greater than 4, unless you have a Hab Complex.  In WTP that's not true.  I was quite surprised to see one of my bases at size 5, before I had completed a Hab Complex.  This is because WTP implements a growth penalty rather than a growth limit.  The Morganic faction description should say something about a growth penalty instead of can't get bigger at all.  I'm afraid I don't know exactly what to say, as I only just figured all this out and haven't wrapped my head around how growth now actually works.

**Comment by tnevolin** [comment]
I have modified description for population facilities. We can say same for Morganites.

**Comment by bvanevery** [comment]
The issue is not present in version 252.
