### ISSUE TITLE
alphax.txt says Children's Creche gives Growth/Effic/Morale

### ISSUE THREAD

**Issue by bvanevery** [tnevolin/thinker-doer#66]
This is wrong.  In WTP the Children's Creche does not give any Morale bonus, according to its modified Datalinks.  The short description line in alphax.txt should be changed.

**Comment by tnevolin** [comment]
One more place to update help. Will commit in next version. Is this short description shown anywhere in the game?

**Comment by bvanevery** [comment]
Yes, those short descriptions are shown when you have a table of icons in front of you to pick something you're going to make at a base.
