### ISSUE TITLE
Data Angels SHARETECH description is wrong

### ISSUE THREAD

**Issue by bvanevery** [tnevolin/thinker-doer#68]
WTP, like my own mod, went to a SHARETECH regime for gaining techs.  Anything known to 3 factions, the Angels get too.  No infiltration required.  But their faction description says they have to infiltrate.  They don't; the bit about needing to infiltrate should be snipped from the description.

**Comment by tnevolin** [comment]
Removed in future versions.

**Comment by bvanevery** [comment]
This description bug is present in version 252.

**Comment by tnevolin** [comment]
Let me check it out when I am back from vacation.
