### ISSUE TITLE
University eradicated twice in a row

### ISSUE THREAD

**Issue by bvanevery** [tnevolin/thinker-doer#71]
I have a vague memory of seeing this problem in a previous build of WTP.  This is the 2nd time in a row I've gotten this message.  Saving a game.  This is the beginning so I have no idea what's going on with them.  You can inspect it yourself with the Scenario Editor; I'm doing reasonably well with the Gaians and am not going to quit.
![2nd University eradication](https://user-images.githubusercontent.com/734930/116006709-691e9e80-a5da-11eb-8598-291e9fecd9bb.jpg)
[Deirdre of the Gaians, 2121.zip](https://github.com/tnevolin/thinker-doer/files/6372796/Deirdre.of.the.Gaians.2121.zip)
There were no further recurrences, so at least it wasn't infinite death and resurrection.

**Comment by tnevolin** [comment]
Would you mind to give me save with the turn **prior** to that?

**Comment by tnevolin** [comment]
I loaded this save and I see University is respawned at some spot with all the colonies and formers. I cannot tell what happened on turn before. Could be that they are indeed eliminated by worms or something. Cannot tell without previous turn save.

**Comment by bvanevery** [comment]
Too late.  I'm way farther into the game now, and saves have long since been overwritten.  Your WTP doesn't have the "save for every turn" feature.  If I ever see this again, I'll try to remember to grab saves from multiple previous turns.

**Comment by tnevolin** [comment]
I am going to close it for now as I don't understand how to reproduce it.
Please turn auto saving on for future. It keeps 5 previous turn saves on disk.
I think I have fixed something related to eradication in the past. Not sure if it this one, though.
