### ISSUE TITLE
Morganite -1 SUPPORT penalty is crippling

### ISSUE THREAD

**Issue by bvanevery** [tnevolin/thinker-doer#73]
This was true in the original game as well.  They were the worst faction bar none.  Just like the original game, +1 ECONOMY doesn't really do you any good.  You still have to go Free Market to get to +2 ECONOMY or higher and the vaunted 1 energy per square.  Wealth doesn't come until a lot later.  Meanwhile the Morganites have a really hard time scouting and expanding in the early game, due to lack of SUPPORT when it actually matters.  Plus they get the Hab limitation.

I'd just get rid of the SUPPORT penalty.  It seems you actually like to have faction disadvantages, rather than set everyone to a baseline of zero like I did in my mod.  Just remember that they've still got a Hab limit, and that making +1 ECONOMY isn't much of an ability anyways.

**Comment by tnevolin** [comment]
I don't have an opinion on that but generally prefer not to change factions if possible. It is difficult to integrate them with other text mods then. If you can collect a few more similar opinions I would be happy to comply.

**Comment by bvanevery** [comment]
> It is difficult to integrate them with other text mods then. 

I don't understand this concern.  Who in the real world is downstream of your work, integrating with your work, and putting their work in front of the public?  I've heard of no such person.

If there were such a person, the physical act of integrating, is dropping *.txt files onto a directory.  That doesn't change anything about what you provide as default factions.  It only implies that someone may overwrite them.

Admit it: you actually hate balancing factions, because it is a _lot_ of work.  You want to offload this concern to someone else.  I'm trying to get you to see, that it's necessary work, and nobody's actually gonna do it in the real world.  'Cept you.

**Comment by tnevolin** [comment]
MercantileInterest for one. However, you are right. Maybe I am extra cautions at that. And I admit - I don't like balancing factions. I tried it some time ago but didn't find any satisfactory solution. And yes. It is a lot of work.
Go ahead and propose your faction set. I am sure you have something in mind based on your feedback.

I personally consider faction traits as salt in a game that adds to playability but is nothing comparing to regular SE choices and/or starting luck. Like landing in jungles overcomes any faction weaknesses 10 times, for example.

**Comment by bvanevery** [comment]
I will never propose for you, a faction "set".  I believe in fixing one damn thing at a time, according to real world playtesting and running AI vs. AI games.  When a faction underperforms, or sucks to experience, I do something about it.  Anything I've put in your Issue Tracker, meets that bar.

When you adjust 1 thing, there is the potential for something else to change.  Not so bad with factions if you only move 1 variable up or down 1 at a time by 1 number.  But if you start making a bunch of changes with a faction, you can definitely overcorrect.  Don't care to.  The reason I deployed my changes, any given release, was to put them under some kind of test.  I always _thought_ they were good, when I released them, but subsequent playtesting has a way of shaking out assumptions.

I don't agree with your dim view of factions.  Of course, I'm the guy who actually put the work hours in, to try to make them all different.  They even have nominally different static AI strategies.

**Comment by tnevolin** [comment]
Very well. Let's do one thing at a time.
This is Morgan's only SE penalty. I think without it they will be too strong. Do you propose just remove it without replacing by anything else?

**Comment by bvanevery** [comment]
As I said before, a SE penalty is not the only kind of penalty.  I think you are like the original devs.  You grossly overestimate the value of +1 ECONOMY.  There's no empirical basis for it.  I've watched various Morganites fight gazillions of times.  Me vs. them, AI vs. AI.  _My own_ Morganites ended up at +1 SUPPORT.  In my view, just ridding them of -1 SUPPORT is conservative.

Paper calculations of what "should" matter, don't count.  The game is a real system of real code interactions.  It is tempting for the mathematically inclined to search for closed-form solutions to problems they want to understand.  Well I have the stacks and stacks of engineering notebooks, 3 decades worth, to say it _doesn't work._  I've mostly given up on closed form equation answers to questions as a complete engineering waste of time.

**Comment by tnevolin** [comment]
I don't understand about any kind of player advantage. Are you saying all faction should have mostly positive bonuses?

**Comment by bvanevery** [comment]
No I'm saying that as a designer, you don't think about what a faction is supposed to be _good at_.

Morgan is supposed to be good at money.  If he's only marginally better than all the other factions at making money, then he doesn't have an advantage.

Lal is supposed to be good at getting votes and getting a big population.

Zhakarov is supposed to be good at research.  If everyone else gets techs quickly, and trades them readily because they don't block on most SPs, and anyone can steal from very broad undefended empire fronts from all the colony spam, then Zhakarov doesn't have any advantage.  Furthermore he has onerous penalties, for this advantage he doesn't actually possess.  I'm pretty close to "calling it" on Zhakarov as a bad faction, same as Deirdre and Morgan, but I'll suspend judgment until the next time I see my "more refined" early mining strategies in action.

Yang is supposed to be good at Police.  I just quit a game with him.  I never learned Police State.

At least Santiago is actually good at war.  +2 MORALE is hard to undo.  Some benefits are clearly worth way more than others.

It's not supposed to be, player has a hard time in every direction.  Player is supposed to have a good time exerting their _advantage_ at other factions' expense.

**Comment by bvanevery** [comment]
Being able to win with any faction, doesn't prove that Morgan is balanced.  It only proves that you know how to play the game fairly well.  Not everyone has your skill level.  I also notice in your game, you started with Rainy land and didn't have any land enemy next to you.  You had a "good" start.

Factions don't have "original" balance because WTP has different SE choices, a different tech tree, and different AI behavior.

**Comment by afwbkbc** [comment]
I mean that I didn't feel any problems with low SUPPORT, at all, also Morgan does not need big industry, this faction is about economy and just buying ('HURRY') buildings/units/whatever as needed.
I didn't have much 'Rainy' land, I just looked for such spots for first bases and then went mass condensers.
Also I had Rose nearby which was top 2 on charts (more than 5x higher than me) and started to become top 1 by the end.

"Being able to win with any faction, doesn't prove that Morgan is balanced"
yes, but not being able to win with any faction, doesn't prove that Morgan is not balanced :)

**Comment by bvanevery** [comment]
You had plenty of Rainy land for the beginning of a game.  A "bad" start would be getting stuck somewhere that's dry as bone.

I take it you went Free Market.  If you hadn't, does Morgan actually have any advantage?  I don't think he makes much more money with his +1 ECONOMY than anyone else would.  It doesn't buy him any SE freedom until Wealth is available, and that's solidly midgame.  Generally speaking, advantages available at the beginning of the game, are worth way more than so-so advantages later in the game.

> not being able to win with any faction

is not an issue under discussion.  I don't know if you realize, but I'm one of the arch-modders of SMAC.  I can of course beat the original game on Transcend with any faction and random combo of factions.  It's the only way I played for a few years before I started modding.

I guess we'll need to come to semi-agreement on what "balanced" means.  I'll look at your video to see how you won the game.

**Comment by afwbkbc** [comment]
Just an average amount of Rainy land *shrug* 
Yes, I went Free Market asap and a bit later also Police State to balance both SUPPORT and POLICE. As soon as Wealth became available I switched to it and disabled Free Market, and then war started so I went Fundamentalism + Green (and later +Power and was close to Thought Control aswell).

> the original game on Transcend
it's just too easy, AI are very stupid there

> I played for a few years 
not trying to brag, but I started playing smac (multiplayer) in early 2000s and continued more or less regularly until now, so I know a thing or two about balance :)

> Hmm, by the end of almost 8 hours of video, you hadn't won the game. 
yes after I saw my entire army bought up by one probe I considered this particular match bugged and ended it there. In next games I'll pay extreme attention to any possible probe, until they get some nerf.

> The graph said
the graph said I'm on Transcend difficulty, you can't just outmacro AIs in early-mid game :)

> I saw an energy market crash event near the end of the video, which means you were not rich, and not poised for Economic Victory
yes by the end I switched to more regular warfare to withstand pressure from Hive and Rose, I wouldn't survive till Economic Victory if I kept free market and stuff.

> Judging by enemy city sizes, there's no way you had the population for Diplomatic Victory.
in most games I aim to win by conquest, so ignoring other options (unless I see VERY favourable conditions). Conquest is safest bet imo.
Also, not sure if you noticed, but I played with 'Opponents more agressive' setting *shrug*
But dw it was just my first game with this mod, just tested various things. Beating Transcend is a matter of time :)

**Comment by bvanevery** [comment]
I have also played SMAC since it originally came out, on and off.  I only included my most recent full-time experience prior to modding, to indicate that my iterations upon the game, are pretty fresh.

>I played with 'Opponents more agressive' setting

That merely makes them suicidal and easier to dispatch.  It is dangerous in the early game at close range only.  Otherwise it is having the AI throw away units over and over again on your superior terrain positions.

Probe teams are horribly overpowered in the original game, and caused me more rage quits than any other feature, by an order of magnitude.  I don't know how WTP stands in this regard.  I doubled mind control costs in my own mod.  The Data Angels now get the costs of a normal original game faction, 1x cost.  I have the Hive and the Cyborgs getting 1.5x cost.  Everyone else gets 2x cost.

>  But dw it was just my first game with this mod, just tested various things. Beating Transcend is a matter of time :)

I think the only thing your video proves, is as the Morganites you didn't get killed.

**Comment by afwbkbc** [comment]
> Otherwise it is having the AI throw away units over and over again on your superior terrain positions.

the new AI plays smarter than that though

> I doubled mind control costs in my own mod.

the main issue is not price but that units residing in city are completely ignored while calculating cost, hence one can just lure enemy armies to 'capture' himself and then cheaply buy it all and win.

**Comment by bvanevery** [comment]
> the new AI plays smarter than that though

I have not played the most recent versions of WTP.  Previously, I saw no evidence of offensive competence at all.  The difficulty of winning was more like... the never ending swamp around you.  Whether one could stand to wade into it or put up with it.  I have not won WTP recently.  I've ended up quitting mid-game at best.

I filed some Issues that I was pretty clear on, after repeated plays of early to mid game.  Then I begged off.  Went back to working on my own mod for a bit, and also playing some 4X RPG thing, which has in turn started to bore me.  Not quite ready to resume WTP testing.

**Comment by tnevolin** [comment]
> yes after I saw my entire army bought up by one probe I considered this particular match bugged and ended it there. In next games I'll pay extreme attention to any possible probe, until they get some nerf.

If you say you are quite a seasoned player you should know the power of mind control from vanilla. Nothing changed in WTP regarding that.

**Comment by tnevolin** [comment]
Regarding number of units AI produce: I am working on it trying to make them produce more without breaking much else. Otherwise, I just can let them stump units only disregarding everything else, which is also stupid.

If you still find WTP AI toothless try to switch off WTP AI algorithms completely (thus defaulting to Thinker 100%). I am not entirely convinced that Thinker does it better but still worth trying and comparing.

**Comment by afwbkbc** [comment]
In Vanilla AIs used probes less often, nowadays it's their #1 tactic and most city they get is by mind controlling.
tbh, on Transcend AIs can just spam probes and ignore other units and win :)

**Comment by tnevolin** [comment]
If they are so effective then Thinker/WTP does right thing by increasing their production. Doesn't it?

I think you exaggerate things about defense uselessness. One can as well produce just more defensive probes instead of wall of units. Defensive probes can be infantry ones since they are stationed in bases. They are 50% cheaper. In addition they receive 50% defense bonus in base and 25% from sensor. Combined number above player needs to invest into probes only 0.36 of what AI invested in them. That is an awesome advantage because the rest of it can be invested in units to continue the advance. This is quite far from being not useful. Is it?

Admit it. You have played years against exceptionally stupid AI and worked out perfect strategy. Now you are caught off guard by slightly smarter AI trying to get to you by  somewhat different tactics and you refuse to change yours in response. You would better go back to previous stupid AI just to not alter your routine?
😉

**Comment by afwbkbc** [comment]
> If they are so effective then Thinker/WTP does right thing by increasing their production. Doesn't it?

Umm, well, I mean AI abusing overpowered and broken mechanics is of course smart, good for them! The problem is not about AI, the problem is about existence of overpowered mechanics (in this case - ones that are exclusive to Transcend AI since they will always have enough energy to mind control another city).
Yes, strategy can be built around acceptance of overpowered units and mechanics in game. Does it make game more fun? Not really, as of now it's more like 'probes tag' game instead of allowing big variety of strategies and tactics.

> You have played years against exceptionally stupid AI and worked out perfect strategy.

yes, AI didn't abuse overpowered units so it was 'kinda' ok, but problem was there too, just hidden. Now it's same problem but visible.

> Would you better go back to previous stupid AI just to not alter your routine?

no, I'd like AI as smart as possible but without overpowered units and features in game itself.

> I didn't change much regarding probe production and movement in WTP so this aspect should be about the same.

yes, probes were broken in Vanilla too, but maybe we can fix them here finally, at least prevent cities mindcontrolling rampages (not by nerfing AI but by nerfing actual units).

**Comment by bvanevery** [comment]
With the new SUPPORT rules, -1 SUPPORT still gives 2 free units at the beginning of the game.  It is not materially different from 0 SUPPORT as far as immediate effects with a few units.  This makes the Morganites no longer crippled.  I just tried them in version 252 and didn't have any particularly difficult time doing stuff with them.

**Comment by tnevolin** [comment]
Cool. Let us keep it this way then!
