### ISSUE TITLE
Please consider not storing releases in git repo

### ISSUE THREAD

**Issue by Voker57** [tnevolin/thinker-doer#74]
The whole point of git is that history is always available. If you make tags, people can always obtain past release version 
(git archive). Storing zips in git is useless and just wastes space on clone.

**Comment by tnevolin** [comment]
Thank you for pointing this out.
Some people don't know git but still want to get their version zip file. What is the option for them?

**Comment by Voker57** [comment]
> Thank you for pointing this out.
> Some people don't know git but still want to get their version zip file. What is the option for them?

Git automatically packages tags in zip files, just push a tag and it will be available to download from releases.

**Comment by tnevolin** [comment]
**WHAT** does it automatically package in zip files? I don't think it will package them as I want to.

**Comment by Voker57** [comment]
> **WHAT** does it automatically package in zip files? I don't think it packages what and how I want it to.
> This is a custom zip with some structure and selected files in it.

Ah, you're right, sorry. You'd have to set up a actions to build release files https://docs.github.com/en/actions/learn-github-actions, or use something like https://github.com/itsmattkc/uploadtool to upload them manually.

**Comment by tnevolin** [comment]
Yes. I am looking at this and should probably try to upload them manually to exclude from code base. Thank you for pointer!
I will see how it works in next release.
