### ISSUE TITLE
Probes with armor that cost no support should be fixed

### ISSUE THREAD

**Issue by afwbkbc** [tnevolin/thinker-doer#77]
Now it's possible to spam 'defensive probes' (0-5-2 etc, AI does that aswell) that cost no support and just stuff cities with them for infinite defence against anything.
Either probes should not be able to defend vs combat units, or they must cost support too.

related problem: if tile has 0-5-2 probe and 0-2-1 sentinel on it then, if attacked, sentinel will defend first (and die), despite probe having stronger defence (I think even former would defend first).

Maybe just revert probes to original?

**Comment by tnevolin** [comment]
This is the original. You can do the same in vanilla too!
😁

Making them use support - good idea. This forces player to be more mindful about building them.

**Comment by afwbkbc** [comment]
In vanilla you could but armor wouldn't help when attacked by combat units (probe would have strength 0 anyway).

Also, one more related problem - if there is a base with one military unit (i.e. scout patrol) and 5 defensive probes (0-5-2) then when attacked scout patrol defends first, dies, and then all probes are destroyed aswell ('you destroyed 5 units' message or something).

**Comment by tnevolin** [comment]
![armored_probe](https://user-images.githubusercontent.com/830161/118002130-5532a680-b315-11eb-9487-99f9f3948ad0.png)

Where did you get your facts from??? The mechanics is absolutely same as in vanilla.

I understand the probes not chosen as best defender and dying with them. I guess this is how it was designed in vanilla with probe being special unit that should not rush into combat and die without support. I don't see this as a huge problem. Yes one would lose all higher armored probes if they are caught in such stacked fight. What precludes player from protecting them with equally armored defender if they already discovered this armor?

I don't see easy solution for this. Disabling armor on probes seems to be the easiest. From the other side it weakens the AI probes as they become exceptionally vulnerable en route. Armor gave them some extra protection from conventional attacks.

**Comment by afwbkbc** [comment]
Huh? Are you sure this screenshot is made in Vanilla (not just terranx.exe, but whole directory unmodified)?

**Comment by tnevolin** [comment]
Positively 100%. I just installed fresh from GOG into empty directory. Verify it yourself just to make sure.

> yes thats why probes needed to have combat units defending them.

And AI sucks at it. It actually sucks at unit coordination in general. What are we going to do? Invest thousands of work hours into fine tuning it? Not happening. We are not building a perfect game here. Just merely try to approach it the easiest way possible.
😥

**Comment by tnevolin** [comment]
Probes now require maintenance always regardless of their armor. Don't remember which version I've added it. Should solve the headline problem. I am going to close this.
