### ISSUE TITLE
Marine Detachment is a bit overpowered

### ISSUE THREAD

**Issue by afwbkbc** [tnevolin/thinker-doer#79]
In my yesterday's game ( https://www.youtube.com/watch?v=XPH0-oMPmBk ) I was able to completely control left flank with several Marine Detachment cruisers (then almost tripled fleet just by capturing enemy ships there), I feel like chance is around 75%? It has big possibility to snowball out of control (captured ships are also often Independent), it was like that in Vanilla too, yes.
Proposals:
make chance 25% ?
make Marine Detachment module more expensive?

**Comment by tnevolin** [comment]
Makes sense. If making it more expensive - how much you think it should cost?

**Comment by afwbkbc** [comment]
Maybe double the amount they cost now?
Nautilus Pirates gets them for free but I don't see it as problem, that faction is weak in many other aspects so need something.

**Comment by tnevolin** [comment]
https://github.com/tnevolin/thinker-doer/releases/tag/234
