### ISSUE TITLE
Psi-weapon has its use

### ISSUE THREAD

**Issue by Heimdell** [tnevolin/thinker-doer#80]
A Copter with psi-weapon can attack a number of times equal to its remaining movement points.

**Comment by tnevolin** [comment]
Thank you for pointing this out. Although copter can attack once per remaining turn regardless of weapon installed. Psi weapon doesn't add anything to this functionality.

The reason I have disabled psi weapon/armor is the inherent vanilla design bug. Hard-coded all over the code it determines whether unit is "psi unit" by checking its weapon offensive value being less than zero only. Then it applies special rules to such units. Therefore, predesigned unit with psi weapon will qualify as psi unit even if it is engaged in conventional combat on defense. At the same time predesigned unit with psi armor will not qualify as psi unit even if it is engaged in psi combat on defense. That creates a lot of inconsistencies in game those are exceptionally difficult to fix. So it is better off to just exclude them.

**Comment by tnevolin** [comment]
I'll close it if you have no other suggestions.
