### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by tnevolin** [tnevolin/thinker-doer#84]
Version: 229, 240

Game crashes after end of human turn during AI turn phase.

[Aki Zeta-5 of the Consciousness, 2153.zip](https://github.com/tnevolin/thinker-doer/files/6602763/Aki.Zeta-5.of.the.Consciousness.2153.zip)

**Comment by CaptEHCJ** [comment]
[SMAX.zip](https://github.com/tnevolin/thinker-doer/files/6603587/SMAX.zip)
Here are the following:
alphax.txt
conceptsx.txt
helpx.txt
labels.txt
Script.txt
socwin.pcx
terranx_mod.exe
thinker.dll
thinker.ini
Alpha Centauri.Ini

**Comment by CaptEHCJ** [comment]
I am launching the game by running the following via an icon shortcut:
"C:\Program Files (x86)\GOG Galaxy\Games\Alpha Centauri\terranx_mod.exe"

and I will attempt to upload the entire Alpha Centauri folder in a zip next...    it is 497M in size.

**Comment by CaptEHCJ** [comment]
Nope.. not allowing me to upload a file that large.  Please let me know if you need any other files to further test... thanks kindly.

**Comment by CaptEHCJ** [comment]
And to answer the other question, when I "complete" my turn and hit enter, the game immediately crashes or closes.  No warning, heads up, errors, etc.  Just Poof gone.

**Comment by tnevolin** [comment]
Try 243 with the same save.

**Comment by CaptEHCJ** [comment]
Bingo - 243 installed and now it does not crash.  Whatever you did surely fixed it.  Thank you so much!!

**Comment by tnevolin** [comment]
You are most welcome.
