### ISSUE TITLE
wrong Alien faction descriptions

### ISSUE THREAD

**Issue by bvanevery** [tnevolin/thinker-doer#89]
Neither Alien has Recycling Tanks anymore.  They both have a -1 INDUSTRY penalty that is not described.

**Comment by tnevolin** [comment]
Damn. So many descriptions to keep in sync. I wish someone could do this for me.
😀

**Comment by bvanevery** [comment]
Don't look at me.  At this point you're lucky I even playtest.  It's a _lot_ of hours.

**Comment by tnevolin** [comment]
Not at you specifically. Just a wish.

**Comment by tnevolin** [comment]
#256
