### ISSUE TITLE
cannot move into square occupied by my own probe team

### ISSUE THREAD

**Issue by bvanevery** [tnevolin/thinker-doer#93]
![probe team does not control its square](https://user-images.githubusercontent.com/734930/126049553-3de03ac3-9c32-4212-9f61-f7abe8b2bf11.jpg)

In the picture, I'm trying to move my Recon Speeder into the square occupied by my Probe Team, to then kill the Hive's nearly dead Recon Speeder.  I can't do it.  It's as though my Probe Team does not exist in its square.

**Comment by tnevolin** [comment]
WTP does not allow ignoring ZOC while moving to the tile occupied by your probe team only. There should be some other non probe on this tile to ignore ZOC. That is a feature.
