### ISSUE TITLE
cannot sabotage Hive perimeter defense

### ISSUE THREAD

**Issue by bvanevery** [tnevolin/thinker-doer#94]
![probably 6th team to sabotage this sea base](https://user-images.githubusercontent.com/734930/126049701-1ac8d114-5459-4eb9-960e-00513a8d53a6.jpg)
I've sabotaged this base with probe teams over and over again.  Maybe 6 times.  Every time, it sabotages only the hab complex and then it goes right back to building it all over again.  It's as though the perimeter defense is not eligible for sabotage, either by immunity to sabotage, or by non-existent probability of being selected for sabotage.  In the stock game, a perimeter defense that's bestowed as part of a faction's ability, is not invulnerable.  Only the Citizens' Defense Force is invulnerable, and you can question whether that's a feature or a bug.
![Hab Complex barely begun yet again](https://user-images.githubusercontent.com/734930/126049731-e490e8a6-1b8b-4fe4-8231-634714b49a1c.jpg)
![I only stir things up, to increase success rate](https://user-images.githubusercontent.com/734930/126049750-2dbce1e4-3287-4400-be32-70fb260e0f79.jpg)
![this always happens](https://user-images.githubusercontent.com/734930/126049768-13452887-17e7-4c0a-bd02-7501471fb166.jpg)
![it'll start again next year](https://user-images.githubusercontent.com/734930/126049797-8eb19bf4-499e-4db6-aab3-1e28d970739f.jpg)
I've only ever hit it with 1 probe team at a time, because the distance to get there is long and the sea defense is too good to mass my units.  They are always in danger of getting picked off by either Hive or Believer ships, who are allied with each other.  I shouldn't be required to have 2 probe teams to take out any particular random facility anyways.
[Lal of the Peacekeepers, 2270.zip](https://github.com/tnevolin/thinker-doer/files/6835321/Lal.of.the.Peacekeepers.2270.zip)
![only a Scout](https://user-images.githubusercontent.com/734930/126050536-5cceb30b-4cc1-4b5f-990e-60bb1b7d0b35.jpg)
I tried another base that didn't have any facilities except the Pressure Dome and the Hive's perimeter defense.  It had a Trance Scout in production.
![Scout gets preferential treatment](https://user-images.githubusercontent.com/734930/126050571-dea5131e-8e41-4803-a6c3-715e181c1aac.jpg)
The perimeter defense is not sabotaged.  Instead the Scout production is terminated, which is all but useless as it's a permanent state of never ending spam.  Even 1 mineral into production, would result in a sabotage going towards terminating production.

![ready to double strike](https://user-images.githubusercontent.com/734930/126053781-6fced2d5-3c4e-4fe3-8024-a36da101243e.jpg)
I finally got 2 probe teams into position to sabotage the base on the same turn.
[Lal of the Peacekeepers, 2283.zip](https://github.com/tnevolin/thinker-doer/files/6835576/Lal.of.the.Peacekeepers.2283.zip)
![hab complex destroyed](https://user-images.githubusercontent.com/734930/126053815-6e7d6af4-5c82-449c-8b2b-51d239e5390f.jpg)
1st team terminates the Hab Complex production.
![hab complex production already terminated](https://user-images.githubusercontent.com/734930/126053828-7899b3bf-ed31-40ef-b7fa-119ed5227a5d.jpg)
2nd team merely terminates the Hab Complex production again, even though there's no work done on it.

**Comment by tnevolin** [comment]
WTP does not allow to sabotage defense facilities **at all**. This is a feature.
