### ISSUE TITLE
AI puts ECM on ships

### ISSUE THREAD

**Issue by bvanevery** [tnevolin/thinker-doer#95]
alphax.txt does not allow the Comm Jammer on either ships or planes.

I was surprised to be attacked by an ECM Plasma Hoverboat, because I'm not allowed to design those.  The ship died, and I'm not sure if the AI is making a great habit of it, as the Cult of Planet seems to have only ever produced 2.  I don't know if this is from straightforward design, or a bug in ship designs getting turned into something else.  Sometimes even in the stock binary I've had my suspicions that designs can get converted from one thing to another.  I'm not sure of the circumstances, but I suspect something to do with upgrades.

[Svensgaard of the Pirates, 2212.zip](https://github.com/tnevolin/thinker-doer/files/6871922/Svensgaard.of.the.Pirates.2212.zip)

![AI makes ECM Plasma Hoverboat](https://user-images.githubusercontent.com/734930/126857628-83daab4d-e45e-4eed-aebc-d9ab37a4547f.jpg)

MY 2263.  Now the Hive is cheating with ECM Chaos Foils, proving the earlier thing wasn't an isolated incident.
[Svensgaard of the Pirates, 2263.zip](https://github.com/tnevolin/thinker-doer/files/6873371/Svensgaard.of.the.Pirates.2263.zip)
![Hive AI cheating at ship design](https://user-images.githubusercontent.com/734930/126887629-7c53beeb-62c8-4117-801f-645c2702707e.jpg)

**Comment by tnevolin** [comment]
#253
I added some code to prevent it but didn't test it, though.
