### ISSUE TITLE
document in Datalinks that probe team has no ZOC

### ISSUE THREAD

**Issue by bvanevery** [tnevolin/thinker-doer#97]
The entry for Zone of Control in the Datalinks does not explain the WTP feature that probe teams don't exert a ZOC.  In particular the 1st few words of the entry, "Every unit exerts a Zone of Control..." are confusing.  Also that "Units may freely move into squares already containing friendly units" isn't true for probe teams.

**Comment by tnevolin** [comment]
> "Every unit exerts a Zone of Control..."

This is true. Why confusing?

**Comment by tnevolin** [comment]
Updated in 254.
