### ISSUE TITLE
picking Change and then OK, removes completion bonus

### ISSUE THREAD

**Issue by bvanevery** [tnevolin/thinker-doer#99]
![lost my free minerals](https://user-images.githubusercontent.com/734930/130521053-9913821e-d10b-4664-aa12-b4bc74e22578.jpg)
[Cha Dawn of the Planet Cult, 2129.zip](https://github.com/tnevolin/thinker-doer/files/7034966/Cha.Dawn.of.the.Planet.Cult.2129.zip)
I had this Gun Foil with a double row of minerals, white above red.  I selected Change for some reason, looking at other units to verify something for some reason.  I think this act alone, ruined my completion bonus.  I don't think I selected any unit in the unit / facility selection screen.  If I did, I know I only clicked on a Gun Foil.  The completion bonus shouldn't get cancelled out just from looking at part of a UI.

It suggests that some value for the completion bonus is not getting updated somewhere.  I don't know if this behavior is also present in the original game.

I do know that in the original game, if you select a completely different unit, you will lose your bonus. But I don't think you lose the bonus just for looking at the Change screen, or for clicking on the unit that's already being built.

![before clicking on Change](https://user-images.githubusercontent.com/734930/130523439-d8dd881b-bfc6-4d79-a7f8-6ec2c5e5c61a.jpg)
[Cha Dawn of the Planet Cult, 2137.zip](https://github.com/tnevolin/thinker-doer/files/7035058/Cha.Dawn.of.the.Planet.Cult.2137.zip)
Not too many turns later, I got another completion event in the same city.  This time I saved the game before doing anything, so that behavior can be verified.  

![right before clicking on Change](https://user-images.githubusercontent.com/734930/130523833-03b69f81-a73a-4ab0-beb9-988de468ba89.jpg)

Clicking on Change and then hitting ESC to exit the unit/facility selection screen, does not lose the bonus.  Clicking on Change and then hitting Cancel, does not lose the bonus either.  However, clicking on Change and then hitting OK, does lose the bonus.  The unit being produced is highlighted on the selection screen.  
![Change followed by OK](https://user-images.githubusercontent.com/734930/130524063-8219152d-20e3-4cb6-9b46-a5c365546cff.jpg)

**Comment by tnevolin** [comment]
Vanilla bug. I can try to fix it but it happens so rare. Do you think we should bother?

**Comment by bvanevery** [comment]
Only if low effort.

**Comment by tnevolin** [comment]
I didn't analyze it but it will most likely require juggling with backup stored minerals and item switching routines. Some moderate efforts, probably. I'll leave it here for a while.
